### ISSUE TITLE
Property length is measured in bytes, not the number of properties

### ISSUE THREAD

**Issue by bschwind** [toddtreece/mqtt-packet#11]
The spec isn't 100% clear on this, but property length is measured in bytes instead of the property count, so the code in these two places needs to be altered:

https://github.com/toddtreece/mqtt-packet/blob/76ba93210c697de525217b43af34c7581d5cb5fc/src/property.rs#L111

https://github.com/toddtreece/mqtt-packet/blob/76ba93210c697de525217b43af34c7581d5cb5fc/src/property.rs#L60

This can also be confirmed by checking an existing client in WireShark:

<img width="1440" alt="Screen Shot 2019-12-24 at 11 50 42 AM" src="https://user-images.githubusercontent.com/458432/71390435-b6d07300-2643-11ea-9d1e-1eeb08714d64.png">

**Comment by toddtreece** [comment]
@bschwind good catch, thanks! i will PR this fix when i get a chance, but feel free to PR it if you'd like to contribute to the project
